spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://127.0.0.1:3305/connectdb
    username: root
    password: "Tmdwns0624@"
  thymeleaf:
    cache:false



  jpa:
    database-plaform: org.hibernate.dialect.MYSQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
